### ISSUE TITLE
One test method "typeNumber_ValidInput_InitiatesCall" failes to pass on M+ (permissions issue)

### ISSUE THREAD

**Issue by pungrue26** [googlesamples/android-testing#100]
I've read README, and followed instruction, and run the tests, and it simply failed. 

It failed at <code>typeNumber_ValidInput_InitiatesCall</code>method with below stacktrace.

> android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: Wanted to match 1 intents. Actually matched 0 intents.
> IntentMatcher: (has action: is "android.intent.action.CALL" and has data: is <tel:123-345-6789> and resolvesTo: com.android.server.telecom)
> Matched intents:[]
> Recorded intents:[]
> ...
> Caused by: junit.framework.AssertionFailedError: Wanted to match 1 intents. Actually matched 0 intents.

It seems the test failes because of permission. If I install the app and mimic <code>typeNumber_ValidInput_InitiatesCall</code> method's code, a toast saying "this app requires 'call phone' permission to run" pops up.

I may send a pull request to fix this, but it seems this project is not under watch by some maintainers. I can see that there are a few pull requests already, which are months old, without much proceeding. So I am afraid my effort goes to waste.

If there is someone who maintains this project, please ping me back. I will try to fix this, and make a pull request.

**Comment by JoseAlcerreca** [comment]
The problem is worse than it seems. I've disabled that test for now, feel free to make a pull request but I'm afraid there's no perfect way to grant permissions. I tried with UIAutomation but I don't like the approach as it will fail with other locales, for example. Also with a shell command from the test, but it was flaky. Need to investigate more and come up with a good or at least the better solution.

**Comment by Jeferex** [comment]
I added this code to DialerActivity (line 60) and after giving permission to app, the tests work.

```
ActivityCompat.requestPermissions(this,
                    new String[]{Manifest.permission.CALL_PHONE},
                    1);
```

**Comment by JoseAlcerreca** [comment]
If you give permissions to the app, they should always work. The problem is how to automate that.

**Comment by JoseAlcerreca** [comment]
Fixed in https://github.com/googlesamples/android-testing/commit/ed62c450e43f859333b3113d44dd59f75971b529

**Comment by pungrue26** [comment]
Confirmed the problem fixed. Thanks for quick replying and updating! 

Also I want to apologize if I was too aggressive for "months-old-issues" things.

**Comment by JoseAlcerreca** [comment]
No worries. We do have some issues that are hard to close :(
