### ISSUE TITLE
Adb grant permission doesn't work

### ISSUE THREAD

**Issue by nomisRev** [googlesamples/android-testing#101]
https://github.com/googlesamples/android-testing/blob/ed62c450e43f859333b3113d44dd59f75971b529/ui/espresso/IntentsBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/DialerActivityTest.java#L94

This doesn't work in @Before. The permission is only granted after a failed test and process restart when the next test is ran.

When running a sequence of tests this fails because a following test might want to revoke a permission on @Before but that actually doesn't work at all.

**Comment by JoseAlcerreca** [comment]
It does work for us. Can you elaborate? Do you have a log?

A test can't revoke a permission for now.
