### ISSUE TITLE
@SmallTest is deprecated

### ISSUE THREAD

**Issue by aaronbond** [googlesamples/android-testing#108]
it seems as of API 24

**Comment by bootstraponline** [comment]
what is the replacement annotation?

**Comment by aaronbond** [comment]
it seems the answer may be here:

http://stackoverflow.com/questions/38551547/smalltest-mediumtest-and-largetest-deprecated-on-android?rq=1

**Comment by bootstraponline** [comment]
thanks. looks like they moved to a new package.

**Comment by aaronbond** [comment]
it seems that way, it was tricky finding the information. must be a very
recent change.

**Comment by mehrdaad** [comment]
Just a quick question, shouldn't test size annotations be just specified in instrumented tests and not in unit tests?  
Because android studio suggest to add size filters under ``androidTest`` directory.
