### ISSUE TITLE
Share IntentTest

### ISSUE THREAD

**Issue by AshishGWL** [googlesamples/android-testing#109]
How to test share Intent. On tapping share button in my App(which is used to share apk file of my app), an App chooser dialog will pops up, and we didn't find a way to get rid of that which leads to fail all successive testCases.

**Comment by FabioCB** [comment]
Have you tried using Intent stubbing ? 

https://google.github.io/android-testing-support-library/docs/espresso/intents/#intent-stubbing

**Comment by AshishGWL** [comment]
Yes but it doesn't helped. The app chooser dialog remains opened which leads to failing of further testCases.

**Comment by JoseAlcerreca** [comment]
Not sample issue https://google.github.io/android-testing-support-library/support/index.html
