### ISSUE TITLE
How to test REST api with espresso in my Android project?

### ISSUE THREAD

**Issue by soapbravo** [googlesamples/android-testing#110]
Hello.

I'm working with Espresso now, but I can not test REST api functionality. 
Because it needs some delay for response, but the tests are run earlier before response.

So I want to know how to test REST api with Espresso in Android project.

Thanks.

**Comment by JoseAlcerreca** [comment]
Check out https://google.github.io/android-testing-support-library/support/index.html

**Comment by kevin-brotcke** [comment]
You can test a REST api with WireMock. See [http://handstandsam.com/2016/01/30/running-wiremock-on-android/](http://handstandsam.com/2016/01/30/running-wiremock-on-android/).
