### ISSUE TITLE
Can't sync espresso with gradle in Android Studio

### ISSUE THREAD

**Issue by ThanawatMas** [googlesamples/android-testing#116]
The org.hamcrest library failed to resolve

As I try to using a Espresso test on Android Studio 2.2. I found problem that it can't sync gradle with org.hamcrest libs.
Even I include libs in project with manual jar. It's not worked. (QoQ) 
I have no idea to resolve it.

Gradle Message Told:

> Error:Failed to resolve: org.hamcrest:hamcrest-core:1.3
> Error:Failed to resolve: org.hamcrest:hamcrest-library:1.3
> Error:Failed to resolve: org.hamcrest:hamcrest-integration:1.3

**Comment by ThanawatMas** [comment]
Add sample of issue

I had add plugin to project
![testcompile espresso](https://cloud.githubusercontent.com/assets/2458942/19559294/540b1bbc-96f9-11e6-94bf-72835ec05652.PNG)

but, I found that can't found org.hamcrest lib
![testcompile espresso 2](https://cloud.githubusercontent.com/assets/2458942/19559302/5c4506b2-96f9-11e6-8cb3-3dead6009e8d.PNG)

**Comment by JoseAlcerreca** [comment]
Closing as it's not an issue with the samples. Feel free to reopen if it is.
