### ISSUE TITLE
Add demo of testing with Page Object Pattern and Espresso

### ISSUE THREAD

**Issue by sebaslogen** [googlesamples/android-testing#118]
Basic examples are good but large test suites need architecture and order to prosper.
A very good pattern is to organize test code and make it reflect the actual user interface with the Page Object Pattern. In a nutshell, the tests contain objects with API to interact and test each view, so test scenarios become independent of testing details like wich button id is pressed to login.
The pattern is explained in these links and examples:
- http://martinfowler.com/bliki/PageObject.html
- http://docs.seleniumhq.org/docs/06_test_design_considerations.jsp#page-object-design-pattern
- https://medium.com/@sebaslogen/the-evolution-journey-of-android-gui-testing-f65005f7ced8
- https://realm.io/news/kau-jake-wharton-testing-robots/

**Comment by JoseAlcerreca** [comment]
These are the API samples, so we won't be adding more layers. There are other samples like android-architecture that would be a better fit for this.

**Comment by sebaslogen** [comment]
Actually I was not sure on which of the two projects I should open this, I'll move it to the other, thanks!

**Comment by JoseAlcerreca** [comment]
That said, I don't think it's an issue. It's a nice practice if you need it, but I don't think we would benefit that much from it. Maybe you can prove a point in a PR.
