### ISSUE TITLE
Not able to get android ui automator library

### ISSUE THREAD

**Issue by dhirenmudgil** [googlesamples/android-testing#144]
Error:Failed to resolve: com.android.support.test.uiautomator:uiautomator-v18:2.3.2
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/dhiren.mudgil/comms-android-plush-test/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by dhirenmudgil** [comment]
It is fixed.

**Comment by binubeee** [comment]
how did you fix it. Iam facing same issue.

**Comment by dhirenmudgil** [comment]
@binubeee The Owner updated the version in the latest commit. https://github.com/googlesamples/android-testing/commit/9534309e0d09d31516cab29469cb31d7fad41ab7
