### ISSUE TITLE
CalculatorInstrumentationTest not running

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-testing#16]
I get the following error:
> FAILURE: Build failed with an exception.
* What went wrong:
Task 'cleanTest' not found in project ':app'.
* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1.518 secs
Task 'cleanTest' not found in project ':app'.

**Comment by JoseAlcerreca** [comment]
After doing what exactly? From what directory?

**Comment by IgorGanapolsky** [comment]
After importing the project in Android Studio.  From the directory where the file is located.  This is all done in Android Studio, it should be rudimentary.  Right click-the file and run!

**Comment by otw** [comment]
Can you give us some more info, i could not reproduce it locally with AS 1.1 and 1.1.3 build tools. Can you please share your build.gradle files with us + the test class you are trying to run?

**Comment by IgorGanapolsky** [comment]
AS 1.2 beta; build AI-141.1825374.  JRE 1.8.0_40-b26 amd64.  Gradle build tools 1.1.3.  `buildToolsVersion '22.0.1'`
Running CalculatorInstrumentationTest.java.

**Comment by IgorGanapolsky** [comment]
build.gradle file is what's in this GitHub repo anyway.

**Comment by otw** [comment]
i cannot reproduce this with AS 1.2, Plugin 1.1.3 and Build Tools 22.0.1 on Trusty (Ubuntu). Which OS are you on? I'll try to investigate more on this.

**Comment by IgorGanapolsky** [comment]
I am on Windows 10

**Comment by JoseAlcerreca** [comment]
Can't reproduce either. Does `connectedCheck` work?

**Comment by IgorGanapolsky** [comment]
What is connectedCheck?  I am just running the test in Android Studio, I am not picking individual gradle tasks...

**Comment by JoseAlcerreca** [comment]
The run configuration that you choose when you right click should be "Android Application" (the option with the Android icon). Can you remove the run configuration and start again?

**Comment by IgorGanapolsky** [comment]
I got it working.  Apparently one cannot run these test classes individually unless you add dependency on `testCompile 'junit:junit:4.12'`.  Very confusing indeed for newcomers to testing.

**Comment by JoseAlcerreca** [comment]
testCompile is only used for JVM tests, this is an instrumentation test so something else was done.
