### ISSUE TITLE
BasicSample : "Please upgrade JUnit version to at least 4.6."

### ISSUE THREAD

**Issue by kaciula** [googlesamples/android-testing#17]
I'm getting this error when trying to run BasicSample:

:app:testDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:testDebug'.
> Test filtering is not supported for given version of JUnit. Please upgrade JUnit version to at least 4.6.

I am using Android Studio 1.2 Beta 3.

**Comment by JoseAlcerreca** [comment]
Please provide more details. Are you executing from Android Studio? Did you choose an "Android Test" configuration?

**Comment by kaciula** [comment]
I'm not sure where exactly I can choose the "Android Test" configuration. I right click on the test file and select "Run". 

I've now run ./gradlew connectedAndroidTest from the command line and now I see it also works from Android Studio.

**Comment by JoseAlcerreca** [comment]
When you select Run you have two or three options. Choose "Android Test" for instrumentation tests. We are working on making this step clearer.
