### ISSUE TITLE
Emulator tests are flaky

### ISSUE THREAD

**Issue by mhlopko** [googlesamples/android-testing#210]
Hello :)

we see these tests flakily red on the CI every other day. I believe we rerun failing test 3 times to deflake, and this still shows up red (maybe it's worker load dependent). Is there a way to deflake?

https://storage.googleapis.com/bazel-buildkite-artifacts/22422254-3061-47cd-b1c2-9b3a918638b2/ui/espresso/BasicSample/BasicSampleInstrumentationTest_23_x86/attempt_1.log

https://storage.googleapis.com/bazel-buildkite-artifacts/22422254-3061-47cd-b1c2-9b3a918638b2/ui/espresso/IntentsBasicSample/IntentsBasicSampleInstrumentationTest_23_x86/attempt_1.log

Cc @jin

**Comment by jin** [comment]
PTAL at https://github.com/bazelbuild/continuous-integration/pull/346, I've added a flag to run the tests locally instead of the sandbox that should reduce flakes on our CI.

**Comment by jin** [comment]
Should be fixed now.
