### ISSUE TITLE
Please move from native to Skylark rules for external git/http repositories

### ISSUE THREAD

**Issue by aehlig** [googlesamples/android-testing#213]
From version 0.20 onwards, bazel by default will no longer support the native http and git repositories. Please switch to the Starlark versions of those rules.

For more background, see

-  the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion 

- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository

Once migrated, please also file an issue against http://github.com/bazelbuild/continuous-integration to reenable testing of your project as a bazel downstream project.

Thanks,
Klaus

**Comment by mhlopko** [comment]
Hi all, this flag is flipped now at bazel@HEAD and will be the default behavior of Bazel 0.20. I'll disable this project on our downstream pipeline (https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/537#3821f2ca-d998-40cc-aefd-73f1557d8460). Please fix quickly and create an issue at bazelbuild/continuous-integration to reenable. Keep in mind that we are now not catching unintentional breakages of this project in bazel@HEAD.
--

**Comment by jin** [comment]
Still failing because the androidx.test deps are still using native.http_archive. Sending in a fix.
