### ISSUE TITLE
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app and test app differ.

### ISSUE THREAD

**Issue by shivarajp** [googlesamples/android-testing#22]
When Tried to include new version this error is shown, google groups said its fixed but I am still getting this error.

Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app and test app differ.

    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 22
        buildToolsVersion "22.0.1"

        defaultConfig {
        applicationId "com.shivam.espressotest2"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'LICENSE.txt'
    }
    }

     dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.android.support:appcompat-v7:22.1.1'
        compile 'com.android.support:support-annotations:22.1.0'

    androidTestCompile 'com.android.support.test:runner:0.2'
    androidTestCompile 'com.android.support.test:rules:0.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.1'

    }

**Comment by shivarajp** [comment]
configurations.all {
        resolutionStrategy.force 'com.android.support:support-annotations:22.1.0'
    }

**Comment by tentativafc** [comment]
Thanks @shivarajp.

**Comment by train-fans** [comment]
Thank you.

**Comment by noloman** [comment]
Awesome, thanks a lot @shivarajp
