### ISSUE TITLE
Android Testing failing on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [googlesamples/android-testing#226]
https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/13#6dd83578-ede3-4bf4-bd29-fc6d6a6f66e8
Android Testing is failing with `Bazel@Release + incompatible flags` due to 
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/34bf6870dfb715fb6ec0e0d81121469e/external/protobuf_archive/BUILD.bazel:605:1: Traceback (most recent call last):
--
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/34bf6870dfb715fb6ec0e0d81121469e/external/protobuf_archive/BUILD.bazel", line 605
  | internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/34bf6870dfb715fb6ec0e0d81121469e/external/protobuf_archive/protobuf.bzl", line 266, in internal_gen_well_known_protos_java
  | Label(("%s//protobuf_java" % REPOSITOR...))
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/34bf6870dfb715fb6ec0e0d81121469e/external/protobuf_archive/protobuf.bzl", line 266, in Label
  | REPOSITORY_NAME
  | The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
```

However, it is [passing](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/649#1db312ec-679b-4567-a9e7-0288f357cd58) with `Bazel@HEAD`, where `--incompatible_package_name_is_a_function` is already flipped to true.

I don't understand why this is happening, is `android_test_support` embedded in Bazel binary and depends on protobuf? @jin

**Comment by meteorcloudy** [comment]
Ah, I see we have `--incompatible_package_name_is_a_function=false` [in the config file](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/pipelines/android-testing-postsubmit.yml#L6)

This flag is removed recently at https://github.com/bazelbuild/bazel/commit/2b3ad18eec4e6b968d840777249c809e478b2e13, so please remove them from config file.

**Comment by meteorcloudy** [comment]
You can now upgrade protobuf to 3.6.1.2
https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1.2

**Comment by jin** [comment]
Yes, we had the same problem where protobuf was updated and we had to test on the latest Bazel where the incompatible change with REPOSITORY_NAME was enabled. That is why I added the flag workaround.

Will look into this.

**Comment by jin** [comment]
@meteorcloudy Not quite -- 3.6.1.2 is just a tag, but we depend on the individual language releases. The latest release is still 3.6.1 https://github.com/protocolbuffers/protobuf/releases

**Comment by jin** [comment]
We can close this now :smile:
