### ISSUE TITLE
Fix Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [googlesamples/android-testing#239]
This repository isn't compatible with Bazel with the flag `--all_incompatible_changes`.

e.g. it fails with `--incompatible_no_transitive_loads` (https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/56#48b4d6c0-6ef6-4a1a-858c-7a68229fc715):

```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/cc704b3d6f5c2a733329351f1fd5d404/external/android_test_support/tools/android/emulated_devices/macro/make_device.bzl:29:1: file '//tools/android/emulated_devices:macro/emulator_info.bzl' does not contain symbol 'emulator_is_qemu2'
```

Fixing the issues will ensure the code remains compatible with the future changes in Bazel. Let me know if you need any help.

cc @jin

**Comment by jin** [comment]
This is blocked on android-test (https://github.com/android/android-test) pushing out the patch to fix the IC.

Internal context: cl/226047055

**Comment by jin** [comment]
android-test is unblocked, but I discovered more issues.  

Also two blockers that require a new Protobuf release:

https://github.com/bazelbuild/bazel/issues/5825#issuecomment-455266862
https://github.com/bazelbuild/bazel/issues/5818#issuecomment-455263473

**Comment by laurentlb** [comment]
I still see failures with:
* `--incompatible_new_actions_api`
* `--incompatible_no_transitive_loads`
* `--incompatible_disable_deprecated_attr_params`

**Comment by jin** [comment]
Looks like there's a new Protobuf release 3.7.0, let me test it out..

**Comment by jin** [comment]
android-testing itself is fine -- the incompatible changes come from android/android-test and its deps.

Tried to bump android-test's protobuf version to 3.7.0-rc2, but failed: https://github.com/protocolbuffers/protobuf/issues/5696

We also need to bump its usage of rules_kotlin to a commit later than https://github.com/bazelbuild/rules_kotlin/tree/cab5eaffc2012dfe46260c03d6419c0d2fa10be0

**Comment by laurentlb** [comment]
Is it possible to fix at least `--incompatible_no_transitive_loads`?
(Protobuf issue is affecting lots of rules, thanks for filing the bug)

**Comment by jin** [comment]
Thanks for the ping! This dropped off my radar. https://github.com/googlesamples/android-testing/pull/246

**Comment by laurentlb** [comment]
@jin Can you try to update to Protobuf 3.7.1?

**Comment by jin** [comment]
So this is turning out to be more complicated than expected. Protobuf 3.7.1 introduces a dependency on a bind `//external:zlib` target, which is switched to a regular external repository in https://github.com/protocolbuffers/protobuf/commit/f313b9ccf7434e04d233ad2f519affc78a9e26a8, which is not in 3.7.1 yet. I'll bump it to use Protobuf HEAD for today.

**Comment by jin** [comment]
```
ERROR: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c0b8e7c3fe9b878a4633a5ff9d0fc340/external/com_google_protobuf_javalite/protobuf.bzl:127:19: Traceback (most recent call last):
	File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c0b8e7c3fe9b878a4633a5ff9d0fc340/external/com_google_protobuf_javalite/protobuf.bzl", line 122
		rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
	File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/c0b8e7c3fe9b878a4633a5ff9d0fc340/external/com_google_protobuf_javalite/protobuf.bzl", line 127, in rule
		attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR: /usr/local/google/home/jingwen/code/android-test/espresso/web/java/androidx/test/espresso/web/model/BUILD.bazel:13:1: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors and referenced by '//espresso/web/java/androidx/test/espresso/web/model:model'
ERROR: Analysis of target '//:axt_m2repository' failed; build aborted: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
```

The `javalite` branch for protobuf hasn't been updated. https://github.com/protocolbuffers/protobuf/tree/javalite

**Comment by jin** [comment]
Blocked on https://github.com/protocolbuffers/protobuf/pull/6048

**Comment by laurentlb** [comment]
If it helps, rules_closure was updated: https://github.com/bazelbuild/rules_closure/pull/344/files

**Comment by jin** [comment]
That's the main protobuf version. android-test has a dependency on protobuf's javalite rules, and the javalite branch hasn't been updated with the incompatible changes.

**Comment by laurentlb** [comment]
Any update?
