### ISSUE TITLE
Build breaks with `--incompatible_use_python_toolchains`

### ISSUE THREAD

**Issue by brandjon** [googlesamples/android-testing#266]
Created a separate issue from #239 to track this flag flip. The flag is introduced in Bazel 0.25 and will likely be flipped in 0.27.

Example failure [here](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/104#a9e8d6f1-9adc-46a7-8bdd-c798d0e6d8f5/5269-5280). See the migration instructions in bazelbuild/bazel#7899. If you have PY2 targets that use the host configuration, you may need to set `--host_force_python=PY2` in your build until the execution configuration is ready to replace the host config.

**Comment by brandjon** [comment]
Another recent run [here](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1008#614ea0e1-d091-40ff-8f42-d1cb1da698be) with the same issue. (This project appears to also be broken at head, but it looks like the breakage due to this flag flip supersedes it.)

It looks like [this](https://github.com/android/android-test/blob/3597c5c92b191f09935fe6a144254284075a38a9/tools/android/emulator/BUILD.bazel#L121-L135) target in a dependency has no `python_version = "PY2"` attribute but its main file contains Python 2 `print` statements. Filed android/android-test#373.

**Comment by laurentlb** [comment]
cc @jin

**Comment by brandjon** [comment]
Among the [failures](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1014#60e17cd4-fb0a-44d7-9439-db17b3568e59) is the line:

```
File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/071e70e385576fb8ffa2d614db55408e/sandbox/linux-sandbox/1495/execroot/__main__/bazel-out/host/bin/external/android_test_support/tools/android/emulator/unified_launcher_head.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 468
print ''
```

That's a running-PY2-under-PY3 error and it occurs in a target with `host` in the exec path, so that means that adding `--host_force_python=PY2` to bazelrc is also necessary.

I also notice that these recent buildkite runs contain the line

> Fetching android-testing sources at 603a0df70d75e240bfd8a3435483f98c17158082

That's the most recent commit, but it's 5 days old. I take it that a new release still needs to be pushed?

**Comment by jin** [comment]
This should be resolved for this repo in #277, but all downstream users of `android_device` now need to add `--host_force_python=PY2` into their .bazelrc or build flags.

@brandjon do you have an approach where we can annotate this host python version in the BUILD file itself? It's not a great user experience if we want to target a flagless build.

**Comment by brandjon** [comment]
Unfortunately no. The approach should ideally be to set `python_version = ...` like for any other target, but this works by changing the configuration, and the host config doesn't allow transitions. At the same time, we don't want to regress on having PY3 be the default host version, or block the rollout of strict version checking. The long-term solution is to deprecate the host config.

**Comment by jin** [comment]
Thanks for the information. Considering that Python 2 is EOL soon, this seems like a good move to make.
