### ISSUE TITLE
Add example for the usage of ServiceTestRule

### ISSUE THREAD

**Issue by vogella** [googlesamples/android-testing#31]
AFAICS their is no example included for ServiceTestRule. Would be nice to have one in this sample project.

**Comment by otw** [comment]
I'm literally pushing STR sample right now :-), just give me a few.

**Comment by vogella** [comment]
Thanks for the fast reactions!

**Comment by otw** [comment]
Done

**Comment by Eido95** [comment]
Do I need to call `bindService` in each test or I can share the binded service reference across different tests (That means only bind it once)?
