### ISSUE TITLE
Provide a listener or hook in ActivityTestRule to run something after a test is run and before an activity is finished 

### ISSUE THREAD

**Issue by chemouna** [googlesamples/android-testing#32]
I'm trying to write a TestRule that takes a screenshot after a test is run , the code for taking screenshot is working, I'm extending ActivityTestRule but i don't have any hook to run my takeScreenshot method after a test is done but before an activity is finished.
```
//in ActivityStatement 
      @Override
        public void evaluate() throws Throwable {
            try {
                if (mLaunchActivity) {
                    mActivity = launchActivity(getActivityIntent());
                }
                mBase.evaluate();
            } finally {
                // I need to take a screenshot here , maybe something like beforeActivityFinished 
                finishActivity();
                afterActivityFinished();
            }
        }
 ```
maybe ActivityTestRule could have a beforeActivityFinished listener that is invoked just before finishActivity ?

**Comment by nkoroste** [comment]
Did you consider having a more generic screenshot rule that does not depend on ActivityTestRule? The "beforeActivityFinished" spot is basically the same as whatever you put in a method annotated with [@After](http://junit.sourceforge.net/javadoc/org/junit/After.html). With that said, it is hard to inject code into @After from a rule statement. Instead if you have a different rule and you chain it properly with ActivityTestRule it should work. 

Also, ActivityTestRule is open open sourced. See how to contribute [here](https://code.google.com/p/android-test-kit/wiki/ExternalContribution)

**Comment by otw** [comment]
I'm closing this issue as Nick already provided the solution above. Feel free to re-open.
