### ISSUE TITLE
Pressing back button on a dialog fragment 

### ISSUE THREAD

**Issue by chemouna** [googlesamples/android-testing#38]
in a test case when i have my dialog fragment open ```Espresso.pressBack()``` doesn't seem to do anything , i thought it was because it's a DialogFragment so maybe a different window so tried : 
```
onView(any(View.class)).inRoot(withDecorView(not(
                is(mActivityRule.getActivity().getWindow().getDecorView()))))
                        .perform(ViewActions.pressBack());
```
(although i'm not sure about ```onView(any(View.class)) ```) but with that i get 
```
android.support.test.espresso.NoMatchingRootException: Matcher 'with decor view not is <com.android.internal.policy.impl.PhoneWindow$DecorView.....
```

I'm i missing something or is this not supported currently ?

**Comment by JoseAlcerreca** [comment]
Hi chemouna,

Please don't use the samples repo for Espresso issues. 

Anyway, the back button is global so you must be experiencing a sync issue. There's a thread about pressBack() in https://groups.google.com/forum/#!msg/android-test-kit-discuss/-kNWLGBKUJs/bHFqXPV32rYJ .
