### ISSUE TITLE
Cannot run test

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-testing#39]
I cannot run your SharedPreferencesHelperTest.  I get an error:
> IllegalStateException: Could not find matching mockable platform jar.

**Comment by JoseAlcerreca** [comment]
Download it using the SDK manager.

**Comment by IgorGanapolsky** [comment]
Download what,  platform.jar?  Why would I do that.

**Comment by JoseAlcerreca** [comment]
The SDK for the API level you want to be able to mock against.

**Comment by IgorGanapolsky** [comment]
@JoseAlcerreca Your <b>build.gradle</b> says `    compileSdkVersion 22`.  And I already have it downloaded in this screenshot:
![device](https://cloud.githubusercontent.com/assets/201209/8699107/0359c3d4-2ad1-11e5-962f-a8765cf825e7.png)

**Comment by JoseAlcerreca** [comment]
It does seem like a bug then. Are you using 1.3? Looks like the issue has been filed already in https://code.google.com/p/android/issues/detail?id=179548 so I'll close this as it's not related to samples. Thanks!

**Comment by IgorGanapolsky** [comment]
I was able to work around this issue by upgrading to `        classpath 'com.android.tools.build:gradle:1.3.0-beta4'
`
