### ISSUE TITLE
Espresso webview support

### ISSUE THREAD

**Issue by hotchemi** [googlesamples/android-testing#41]
I'm looking for espresso webview sample but can't find it even in the android developers.

**Comment by otw** [comment]
We will have a sample available very soon.

**Comment by hotchemi** [comment]
Alright. I wrote some [sample](https://github.com/hotchemi/espresso-tasting/blob/master/app/src/androidTest/java/espresso/tasting/webview/ShowWebViewActivityTest.java) :-).

**Comment by otw** [comment]
Thanks we are always welcome contributions, if you want to write an advanced sample, here is our Basic sample for now!

https://github.com/googlesamples/android-testing/tree/master/ui/espresso/WebBasicSample
