### ISSUE TITLE
BySelector-hasDescendant  Have a Bug

### ISSUE THREAD

**Issue by fan2597** [googlesamples/android-testing#57]
error：
 public static BySelector hasChild(BySelector childSelector) {
        return (new BySelector()).hasChild(childSelector);
    }

    public static BySelector hasDescendant(BySelector descendantSelector) {
        return (new BySelector()).hasDescendant(descendantSelector);
    }

    public static BySelector hasDescendant(BySelector descendantSelector, int maxDepth) {
        return (new BySelector()).hasDescendant(descendantSelector, maxDepth);
    }

They call the constructor error, should call the constructor function to achieve
BySelector(BySelector original)

**Comment by fan2597** [comment]
android.support.test.uiautomator.By
 public static BySelector hasChild(BySelector childSelector) 
 public static BySelector hasDescendant(BySelector descendantSelector) 
 public static BySelector hasDescendant(BySelector descendantSelector, int maxDepth)

**Comment by JoseAlcerreca** [comment]
Please use the android bugtracker for issues related to Espresso, UI Automator, the AndroidJUnit4Runner, rules, etc.
https://code.google.com/p/android/issues/entry?template=Test%20Support%20Library%20bug
