### ISSUE TITLE
Test fails on Android 2.3.6 device

### ISSUE THREAD

**Issue by cmlim** [googlesamples/android-testing#63]
on target device: SHW-M110S 2.3.6
ran test_all.sh with cloned android-testing project
result was as below

ui/espresso/BasicSample :app:connectedDebugAndroidTest
ui/espresso/BasicSample Tests on SHW-M110S - 2.3.6 failed: Instrumentation run failed due to 'Process crashed.'
ui/espresso/BasicSample
ui/espresso/BasicSample com.android.builder.testing.ConnectedDevice > No tests found.[SHW-M110S - 2.3.6] FAILED
ui/espresso/BasicSample No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
ui/espresso/BasicSample :app:connectedDebugAndroidTest FAILED

any clue on this?

**Comment by slinzner** [comment]
Yeah i have seen this before it's on my list!

**Comment by piotrek1543** [comment]
@cmlim, please check if your project is configured properly.
I use for only Espresso these dependencies:
https://gist.github.com/piotrek1543/64514ca2c773d92441c5
and that's my sample Espresso test class:
https://gist.github.com/piotrek1543/e26b85ae3776b3276a32
Hope it help.

**Comment by JoseAlcerreca** [comment]
He(/she) is using BasicSample, so the project should be configured correctly.

**Comment by slinzner** [comment]
Cannot be reproduced on latest emulator image (2.3.7) and latest android gradle plugin version...
