### ISSUE TITLE
[Improvement] More Android testing guides, especially unit and UI testing

### ISSUE THREAD

**Issue by piotrek1543** [googlesamples/android-testing#65]
Hi,

I don't feel comfortable writing unit testing in my Android app. I know how important part of writing any code that is, so I would like you @google-admin @googlebot ask of any useful materials to improve my testing skills.

I really like Udacity courses about Android development, design, performance and much more... but there are no courses about writing test cases. 

Which tools do you recommend and where I can find some about it materials, tutorials?

Regards.

**Comment by IgorGanapolsky** [comment]
There is a Google codelab to get you started.

**Comment by JoseAlcerreca** [comment]
Closing as not related to samples but we got the message, thanks!

**Comment by piotrek1543** [comment]
@IgorGanapolsky, I've already found this site :+1: . Could you give some more related to topic? 
@JoseAlcerreca sorry, but I didn't know where put this message .
Thanks for response
