### ISSUE TITLE
Missing @RunWith(AndroidJUnit4.class) annotation in ServiceTestRuleSample

### ISSUE THREAD

**Issue by qchong** [googlesamples/android-testing#66]
This bug is in reference to this sample:
https://github.com/googlesamples/android-testing/blob/master/integration/ServiceTestRuleSample/app/src/androidTest/java/com.example.android.testing.ServiceTestRuleSample/LocalServiceTest.java

**Comment by JoseAlcerreca** [comment]
Fixed in https://github.com/googlesamples/android-testing/commit/915e3289744c01a62d97f25ca4439a115e882875
