### ISSUE TITLE
dependency not found: androidTestCompile 'com.android.support.test:runner:0.4'

### ISSUE THREAD

**Issue by forrest1g** [googlesamples/android-testing#68]
Run this test project individually, \github\android-testing\unit\BasicUnitAndroidTest\app\build.gradle getting failure: 
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugAnd
roidTestCompile'.
   > Could not find com.android.support.test:runner:0.4.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/test/runner/0
.4/runner-0.4.pom
         https://jcenter.bintray.com/com/android/support/test/runner/0
.4/runner-0.4.jar
         file:/C:/Users/Forrest/AppData/Local/Android/sdk/extras/andro
id/m2repository/com/android/support/test/runner/0.4/runner-0.4.pom
         file:/C:/Users/Forrest/AppData/Local/Android/sdk/extras/andro
id/m2repository/com/android/support/test/runner/0.4/runner-0.4.jar
         file:/C:/Users/Forrest/AppData/Local/Android/sdk/extras/googl
e/m2repository/com/android/support/test/runner/0.4/runner-0.4.pom
         file:/C:/Users/Forrest/AppData/Local/Android/sdk/extras/googl
e/m2repository/com/android/support/test/runner/0.4/runner-0.4.jar
     Required by:
         BasicUnitAndroidTest:app:unspecified

After I downgraded runner to 0.3, test runs successfully.  Are you sure runner of v0.4 is available?
Thanks in advance.

**Comment by cdsap** [comment]
What is your version of Android Support Repository?

**Comment by forrest1g** [comment]
Not installed. Till now I couldn't install it successfully. Is that the reason?

**Comment by piotrek1543** [comment]
@forrest1g change com.android.support.test:runner:0.4 to com.android.support.test:runner:0.4.1.
It should work

**Comment by forrest1g** [comment]
@piotrek1543  it doesn't work for me. version of 0.3 work for me.

**Comment by forrest1g** [comment]
@cdsap I get Android Support Repository installed, its of version 25. Even though runner of v 0.4 still not found.

**Comment by cdsap** [comment]
like @piotrek1543 said with 0.4.1 it should work. 
Take a look this simple build gradle config:
https://gist.github.com/cdsap/341e2292ad37ebe91e40
It's using classpath 'com.android.tools.build:gradle:1.3.0' and android support repository 25.
