### ISSUE TITLE
Taking screenshots while running Espresso test methods

### ISSUE THREAD

**Issue by piotrek1543** [googlesamples/android-testing#69]
Hi,

I would like to ask you about if it is possible to take a screenshot at specifying time while running Espresso UI tests. For example, I'm clicking on floating action button and instantly after clicking take a screenshot to document an action or an error. 

If it is possible, could you explain me how I can do it?

**Comment by cdsap** [comment]
Hi @piotrek1543 I don't think this question is an issue, btw you have screenshot-tests-for-android (facebook), spoon(square).

**Comment by piotrek1543** [comment]
Well, for me issue is not only a bug or an app crash, it's a problem to solve or question to answer. Well, I know both libraries, but i never used them. Because thre's no other answer i will check your, but before I close this issue. 
Thanks for answer.
