### ISSUE TITLE
Add a link to Android Testing Library site to README.md 

### ISSUE THREAD

**Issue by piotrek1543** [googlesamples/android-testing#71]
Hi, 

I think it would be good to add a link to this site https://google.github.io/android-testing-support-library/ in README.md file. 

Sometimes after visit this great repository I need to go to this site to learn something more, but there's no direct link to Android Testinmg Library page. Could you fix it?

Cheers

**Comment by JoseAlcerreca** [comment]
I've been meaning to do that so I'll do it now, the ATSL site is not very discoverable. Thanks!
https://github.com/googlesamples/android-testing/pull/72

**Comment by piotrek1543** [comment]
Thanks for a quick aswer
