### ISSUE TITLE
Test EditText error label test

### ISSUE THREAD

**Issue by SandroMachado** [googlesamples/android-testing#75]
Is it possible to assert the error label on the EditText views using UIAutomator tests?

**Comment by JoseAlcerreca** [comment]
Please check out http://google.github.io/android-testing-support-library/support/index.html

**Comment by piotrek1543** [comment]
@SandroMachado, yes you can assert label of EditText using uiatomator, but why don't you choose for that Espresso. uiatomator is great if you need to check app notifications or permissions.

**Comment by SandroMachado** [comment]
@piotrek1543 the problem is that I cannot make an assert for the `error label`, it works fine for the EditText labels.
