### ISSUE TITLE
Android Studio cannot detect the project and its sub projects, sub modules

### ISSUE THREAD

**Issue by Pedramrn** [googlesamples/android-testing#76]
Hi,
So any solution to that?
It works fine before deleting the root gradle at f16ac90c.

**Comment by piotrek1543** [comment]
You're talking about whole android-testing repo or a specific one. Add more details

**Comment by Pedramrn** [comment]
I mean the whole project, take a look:

![image](https://cloud.githubusercontent.com/assets/7994739/12011385/dc39d78a-acdf-11e5-98fd-90ce3425b426.png)

**Comment by JoseAlcerreca** [comment]
We removed the build.gradle file from top-level because AS does not support this. Open each sample independently.
