### ISSUE TITLE
espresso api typeText doesn't write upper case character

### ISSUE THREAD

**Issue by forrest1g** [googlesamples/android-testing#77]
In the project: android-testing / ui / espresso / BasicSample / , typeText api is called to type "Espresso", but we only see "espresso", upper E doesn't present. Is this a bug of the API? I appreciate if you share thought.  Thank you.

**Comment by piotrek1543** [comment]
I don't think that every failed test must mean a bug. 

I think that test case had been made to show you Espresso's behavior on failed test . 
Nothing less, nothing more.

**Comment by forrest1g** [comment]
@piotrek1543 let me ask in another way: I want to type upper case character, but could't. May I ask how do you achieve that? Thank you.

**Comment by piotrek1543** [comment]
Always you can change this line to lowercase:

    public static final String STRING_TO_BE_TYPED = "Espresso";

to pass a test ;-)

**Comment by forrest1g** [comment]
You must be kidding, but not responding to my question directly. -_-

**Comment by JoseAlcerreca** [comment]
It does write a upper case E.

Are you using the stock keyboard?

**Comment by JoseAlcerreca** [comment]
Closing for now.

**Comment by forrest1g** [comment]
@JoseAlcerreca no, I was using system keyboard. I'm aware some other people reported same thing. What kind of device do you use? that may differ

**Comment by JoseAlcerreca** [comment]
Stock emulators work and Nexus devices work, what device are you using?

**Comment by forrest1g** [comment]
@JoseAlcerreca  it is Meizu m1 note. I will try other device tomorrow. Thanks.
