### ISSUE TITLE
Is there a way to run Uiautomator tests on multiple devices simultaneously?

### ISSUE THREAD

**Issue by seanshi007** [googlesamples/android-testing#79]
I wrote a test class and it contains several test cases, formally in Eclipse it is possible to export a jar file and use adb shell to run it on multiple devices at the same time, but now I am using Android Studio, is there another way to do so?

**Comment by JoseAlcerreca** [comment]
You can still use adb shell to install, uninstall, run, etc.
http://developer.android.com/tools/help/shell.html

We have some examples in
https://github.com/googlesamples/android-testing-templates/tree/master/AndroidTestingBlueprint
