### ISSUE TITLE
The integration service test fails with more than 1 test

### ISSUE THREAD

**Issue by jameydeorio** [googlesamples/android-testing#83]
If you try to write another test with the same setup, the test fails. You can simply copy and paste the one test and rename it to see it happen.

https://github.com/googlesamples/android-testing/tree/master/integration/ServiceTestRuleSample

`java.lang.NullPointerException: Attempt to invoke virtual method 'com.example.android.testing.ServiceTestRuleSample.LocalService com.example.android.testing.ServiceTestRuleSample.LocalService$LocalBinder.getService()' on a null object reference`

**Comment by JoseAlcerreca** [comment]
Please add more details and re-open if still an issue.

**Comment by jameydeorio** [comment]
I posted more details. Maybe I'm confused about the use case, but I want to write several tests in my class which use the service.
