### ISSUE TITLE
The integration service test fails with more than 1 test

### ISSUE THREAD

**Issue by jameydeorio** [googlesamples/android-testing#86]
If you try to write another test with the same setup, the test fails. You can simply copy and paste the one test and rename it to see it happen.

Perhaps I'm using it incorrectly, but I'd like to be able to run all the tests in my test class together.

https://github.com/googlesamples/android-testing/tree/master/integration/ServiceTestRuleSample

```
@MediumTest
@RunWith(AndroidJUnit4.class)
public class LocalServiceTest {
    @Rule
    public final ServiceTestRule mServiceRule = new ServiceTestRule();

    @Test
    public void testWithBoundService() throws TimeoutException {
        Intent serviceIntent =
                new Intent(InstrumentationRegistry.getTargetContext(), LocalService.class);
        serviceIntent.putExtra(LocalService.SEED_KEY, 42L);
        IBinder binder = mServiceRule.bindService(serviceIntent);
        LocalService service = ((LocalService.LocalBinder) binder).getService();
        assertThat(service.getRandomInt(), is(any(Integer.class)));
    }

    @Test
    public void testWithBoundService2() throws TimeoutException {
        Intent serviceIntent =
                new Intent(InstrumentationRegistry.getTargetContext(), LocalService.class);
        serviceIntent.putExtra(LocalService.SEED_KEY, 42L);
        IBinder binder = mServiceRule.bindService(serviceIntent);
        LocalService service = ((LocalService.LocalBinder) binder).getService();
        assertThat(service.getRandomInt(), is(any(Integer.class)));
    }
}
```

`java.lang.NullPointerException: Attempt to invoke virtual method 'com.example.android.testing.ServiceTestRuleSample.LocalService com.example.android.testing.ServiceTestRuleSample.LocalService$LocalBinder.getService()' on a null object reference`

**Comment by tiagozc** [comment]
@jameydeorio 

Look this
https://code.google.com/p/android/issues/detail?id=180396

**Comment by slinzner** [comment]
Thanks. I'm closing this since we have a bug tracking this on the android bug tracker...
