### ISSUE TITLE
Can I use espresso with maven?

### ISSUE THREAD

**Issue by tycallen** [googlesamples/android-testing#88]
Can I use espresso with Maven for UI test? I'm not using gradle because our team's project is using Maven to build.
If it's possible to use Maven, which jar I should import, and which command to run UI test on device?
Thank u.

**Comment by JoseAlcerreca** [comment]
Please check out
https://google.github.io/android-testing-support-library/support/index.html

**Comment by JoseAlcerreca** [comment]
And
https://github.com/googlesamples/android-testing/tree/master/ui/espresso/BasicSampleBundled
