### ISSUE TITLE
UI Automator sample code.

### ISSUE THREAD

**Issue by dino-su** [googlesamples/android-testing#9]
Hi,

Could you please provide sample code for UI Automator sample code with Android testing library (https://developer.android.com/tools/testing-support-library/index.html#UIAutomator), I cannot figure how it works compared to uiautomator.jar (https://developer.android.com/tools/testing/testing_ui.html#classes)

Thanks,
Dino

**Comment by otw** [comment]
Hi Dino,

the uiautomator samples will be available very soon. Hopefully we can do a push this week!

**Comment by JoseAlcerreca** [comment]
Done!
