### ISSUE TITLE
Remove CalculatorTest from androidTest folder 

### ISSUE THREAD

**Issue by codeteo** [googlesamples/android-testing#90]
What's the point having the [`CalculatorTest.java` ](https://github.com/googlesamples/android-testing/blob/master/runner/AndroidJunitRunnerSample/app/src/androidTest/java/com/example/android/testing/androidjunitrunnersample/CalculatorTest.java) class in `androidTest` folder. It isn't android specific. I think it fits better to `test` folder.

**Comment by slinzner** [comment]
Totally right, but we use our samples to run integration tests against the android-test-support-library. That's why we keep it in androidTest/. We might be decoupling them in the future.
