### ISSUE TITLE
calling startActivityForResult from inside fragment

### ISSUE THREAD

**Issue by RameezCharaniya1** [googlesamples/android-testing#91]
I am trying to start new activity from fragment and trying to stub the activity using intentstestrule, but my intent is never caught and execution goes to next activity instead. 

http://stackoverflow.com/questions/37009246/espresso-intenttestrule-onactivityresult-not-called-from-fragment

**Comment by slinzner** [comment]
This is a well known bug. The only way to fix it currently is to go through the Activity, ie. Fragment.getActvivity().startActvivity(Intent). See https://code.google.com/p/android/issues/detail?id=202217
