### ISSUE TITLE
Example using Proguard

### ISSUE THREAD

**Issue by Gregliest** [googlesamples/android-testing#93]
Hi,

It would be awesome if you could provide an example of using Espresso with Proguard.  I've run into multiple issues adding Espresso to an existing project that uses Proguard to stay under the dex limit, and there doesn't seem to be good support available online.  I'll submit a PR if I get it working.  

Thanks!

**Comment by JoseAlcerreca** [comment]
We use proguard in 

https://github.com/googlesamples/android-architecture

**Comment by Gregliest** [comment]
Thanks!  I'll have a look.
