### ISSUE TITLE
Odd NoMatchingViewException 

### ISSUE THREAD

**Issue by busylee999** [googlesamples/android-testing#94]
Hi, time to time I face followed error:
`android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: packetname:id/btn2`

it fire by string
`onView(R.id.btn1)…`

But after rebuilding every things ok.

**Comment by JoseAlcerreca** [comment]
Are animations disabled on your device?

**Comment by busylee999** [comment]
Yes. More than that I do not use R.id.btn2 at all in test yet.

**Comment by JoseAlcerreca** [comment]
Can you give more context to your problem? What project? what test?

**Comment by busylee999** [comment]
Sorry, it is hided by NDA. It seems that it does not depends on project. 
I presume it throws then I continue to write code during running androidTest type configuration from AndroidStudio.

**Comment by JoseAlcerreca** [comment]
Please read https://google.github.io/android-testing-support-library/support/index.html
