### ISSUE TITLE
Accessing button inside iframe via Android Espresso-Web

### ISSUE THREAD

**Issue by FisherKK** [googlesamples/android-testing#95]
Hello,

I am struggling with button click on button which is located inside iframe. Generally website I want to click on is a root that contains only 4 iframes:

```
<html><head>
        
        <style type="text/css">
            html, body {
                margin:0;
                padding:0;
                height: 100%;
                width: 100%;
            }
            .authWindow {
                margin:0;
                padding:0;
                border:0;
                margin: 0 auto;
                width: 100%;
                height: 100%;
            }
            iframe.authWindow {
                display: block;
            }
             
        </style>
        
    </head>
    <body>
              
                 <iframe class="authWindow" src=" url-1 " seamless="" id="auth"></iframe>
                 
                 <iframe src=" url-2 " height="1" width="1" style="position:absolute; top: -10px; left:-10px;" id="profile"></iframe>
                                       
                 <iframe src=" url-3 " height="1" width="1" style="position:absolute; top:-11px; left:-11px;" id="payfone"></iframe>
                                      
                 <iframe src=" url-4 " height="1" width="1" style="position:absolute; top:-12px; left:-12px;" id="rbd"></iframe>
                        

</body></html>
```

And inside first iframe which has id="auth" there is an button which code looks like:

`<input type="submit" onclick="ignoreClose()" name="UsernamePasswordEntry" value="Submit">`

I tried to access it like:

```
Thread.sleep(5000); // I am 100% sure webView has displayed web I am interested in
onWebView(withId(R.id.webView))
    .inWindow(selectFrameByIdOrName("auth"))
    .withElement(findElement(Locator.NAME, "UsernamePasswordEntry"))
    .perform(webClick());
```

But the error I get is:

> java.lang.RuntimeException: java.lang.RuntimeException: Error in evaluationEvaluation: status: 18 value: {message=Blocked a frame with origin "url-1-origin" from accessing a cross-origin frame.} hasMessage: true message: Blocked a frame with origin "url-1-origin" from accessing a cross-origin frame.

Is there any way/workaround to click on such button? Could you suggest me any other tool than Espresso if it's impossible with Espresso?

**Comment by JoseAlcerreca** [comment]
This has nothing to do with Espresso, looks like a security feature.

**Comment by VasilijSviridov** [comment]
same here, anyone found solution for this ? 
webview loads iframe with no issues, but when you are trying to access iframe via .inWindow(selectFrameByIdOrName("auth")) you get that block frame issue.

Any help ?

**Comment by srvsud** [comment]
Same is doable using Apium. So I believe there must be some hook to resolve it using Espresso.

**Comment by pzavadska** [comment]
I didn't find how to access such button using Espresso. It can be done by UiAutomator (https://medium.com/azimolabs/android-webview-automation-testing-6311df8fe42e)
